### ISSUE TITLE
Нужно замыкание при вызове fest:get

### ISSUE THREAD

**Issue by latrekc** [mailru/fest#23]
Пример теста https://github.com/latrekc/fest/blob/7a81908bc7b13b26f80e67696684be85d1d2a42d/tests/templates/need_closure_in_for.xml
https://github.com/latrekc/fest/blob/7a81908bc7b13b26f80e67696684be85d1d2a42d/tests/tests-fest.js#L521

**Comment by AndrewSumin** [comment]
Замыкание есть, но в замыкание передается ссылка на объект, поэтому надо либо передавать примитив, либо формировать новый объект.
