### ISSUE TITLE
<fest:apply />

### ISSUE THREAD

**Issue by eprev** [mailru/fest#51]
Возможность вызвать из `fest:set` ранее определенный `fest:set`.

``` xml
<fest:set name="image">
    <img src="{params.url}" class="image" />
</fest:set>
...
<fest:get name="image">{url: 'https://limg.imgsmail.ru/s/images/logo/logo.v2.png'}</fest:get>
...
<fest:set name="image">
    <div class="image-wrapper">
         <fest:apply />
    </div>
</fest:set>
```

``` html
<div class="image-wrapper">
    <img src="https://limg.imgsmail.ru/s/images/logo/logo.v2.png" class="image">
</div>
```

**Comment by RubaXa** [comment]
Простите, но это неочевидно, совсем.

**Comment by latrekc** [comment]
действительно
почему должен вызываться ранее определенный set? а не просто рекурсия?

**Comment by eprev** [comment]
Название конструкции – не проблема ( `<fest:super />` )

**Comment by RubaXa** [comment]
Даже если рекурсия, то в каком порядке? Это будет по настоящему магический метод!

P.S. Название не причем.

**Comment by eprev** [comment]
В порядке определения (стек).
// Ишью для обсуждения, есть идеи?

**Comment by RubaXa** [comment]
Эээ, и что будет в этому случае?

``` xml
<fest:template>
    <fest:include src="1.xml"/>
    <fest:include src="2.xml"/>

    <fest:set name="image">
        <div class="image-wrapper">
            <fest:apply />
        </div>
    </fest:set>
</fest:template>
```

1.xml — определен set="image"
2.xml — тоже нужен, там были доп. элементы

Через месяц, разработчик "Х" добаляет в файл 2.xml set="image" :trollface:
