### ISSUE TITLE
Предлагаю замену select’у

### ISSUE THREAD

**Issue by eprev** [mailru/fest#63]
Что если убрать `select` атрибут, там где нужны выражения в значениях у фестовых тегов, заменить его на `{ expr }` (как для XML тегов):

``` xml
<f:template>
    <f:get select="json.block" />
    vs.
    <f:get name="{json.block}" />
</f:template>
```

``` xml
<f:template>
    <f:element select="json.block" />
    vs.
    <f:element name="{json.block}" />
</f:template>
```

Получим большую гибкость, например динамические имена атрибутов:

``` xml
<f:template>
    <div>
        <f:attr name="data-{json.blockName}" value="{json.blockValue}" />
    </div>
</f:template>
```

Для предыдущего примера, необходимо было бы заводить `select-name` и `select-value` атрибуты.

Я постоянно вижу как те, кто только начал использовать фест, пытаются использовать `<fest:get name={params.block}/>` вместо `select`.

**Comment by latrekc** [comment]
+1

**Comment by RubaXa** [comment]
:+1:

P.S. Для тикетов нужна голосовалка!

**Comment by AndrewSumin** [comment]
Мы медленно но верно даем писать медленные шаблоны.
Но я не против, звучит логично.

**Comment by RubaXa** [comment]
И где тут медленно? Мы просто убираем лишнюю запись. 

P.S.  Прошу заметить, что пока Антон не занялся оптимизацией fest, он был не таким уж и быстрым, только после оптимизации, результаты стали такими: https://github.com/RubaXa/AsyncTpl/tree/master/benchmark#benchmark
И ничего, работало и работает морде, мы пока не в одном месте не замедлились.
