### ISSUE TITLE
fest:value output="json"

### ISSUE THREAD

**Issue by eprev** [mailru/fest#68]
``` xml
<fest:template>
    <fest:script><![CDATA[var s = "</script>"]]></fest:script>
    <script>var json = <fest:value output="json">s</fest:value></script>
</fest:template>
```

``` html
<script>var json="\u003C\/script\u003E"</script>
```

То есть это JSON.stringify() + замена < и > на \u003C и \u003E

**Comment by RubaXa** [comment]
Что-то типа этого:

``` xml
<fest:var name="s" value="</script>" mode="safeJS" />

или

<fest:var name="s" mode="safeJS"><![CDATA[</script>]]></fest>
```

`<fest:script/>` — это мега low-level и от него вообще нужно постепенно отказываться, выкидывая сначала варнинг, а потом и exception, если явно не будет указано, что для этого шаблона разрешены такие вставки (как jshint ругается на eval).
