### ISSUE TITLE
Mistypes in readme

### ISSUE THREAD

**Issue by viktor-evdokimov** [mailru/fest#7]
&lt;fest:script>var itrerate = {"foo": "bar"}&lt;/fest:script>
&lt;fest:for iterate="itrerate" index="i">
  &lt;fest:value>i&lt;/fest:value>=&lt;fest:value>itrerate[i]&lt;/fest:value>
&lt;/fest:for>

should be 

&lt;fest:script>var iterate = {"foo": "bar"}&lt;/fest:script>
&lt;fest:for iterate="iterate" index="i">
  &lt;fest:value>i&lt;/fest:value>=&lt;fest:value>iterate[i]&lt;/fest:value>
&lt;/fest:for>

**Comment by RubaXa** [comment]
fixed
https://github.com/mailru/fest/commit/9e86749a07331c48ec3d0d85eadbb5f52b42c51c
