### ISSUE TITLE
Переделать все сообщения об ошибках на console.error

### ISSUE THREAD

**Issue by dreadatour** [mailru/fest#70]
Пример: https://github.com/dreadatour/fest/commit/7c8e51163e4f19179d8e73da48514d48bf51bef3#L2R71

В этом случае они попадают в STDERR и, по желанию, легко могут быть либо игнорированы (не очень хорошо), либо обработаны иначе, не так как основной вывод (очень хорошо).

Ну и так как-то правильнее, всё-таки.

**Comment by eprev** [comment]
Будет 0.7.3.
