### ISSUE TITLE
Ошибка компиляции из-за значения атрибута элемента содержащего "{ }"

### ISSUE THREAD

**Issue by Alexsei** [mailru/fest#72]
шаблон:

<pre class="source-code"><code>&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;fest:template xmlns:fest=&quot;http://fest.mail.ru&quot; context_name=&quot;json&quot;&gt;
&lt;div onclick=&quot;func({URL:'/user'})&quot;&gt;&#1057;&#1086;&#1093;&#1088;&#1072;&#1085;&#1080;&#1090;&#1100;&lt;/div&gt;
&lt;/fest:template&gt; 
</code></pre>

Ошибка на: } 

<pre class="source-code"><code>/home/nrad/node_modules/fest/lib/compile.js:756
                throw e;
                      ^
Error: 2: &lt;fest:template xmlns:fest=&quot;http://fest.mail.ru&quot; context_name=&quot;json&quot;&gt;
3: &lt;div onclick=&quot;func({URL:'/user'})&quot;&gt;&#1057;&#1086;&#1093;&#1088;&#1072;&#1085;&#1080;&#1090;&#1100;&lt;/div&gt;
4: &lt;/fest:template&gt; 
At line 3: expression #1 in attribute &quot;onclick&quot; has SyntaxError: Unexpected token :
</code></pre>

**Comment by AndrewSumin** [comment]
``` xml
<?xml version="1.0"?>
<fest:template xmlns:fest="http://fest.mail.ru" context_name="json">
<div onclick="func({{URL:'/user'}})">Сохранить</div>
</fest:template> 
```

Попробуйте так

**Comment by Alexsei** [comment]
Спасибо, так работает.
